"""Verification strategies module — registers all deterministic strategies on import."""

from __future__ import annotations

import backend.services.verification_strategies.blind_sql_injection_strategy
import backend.services.verification_strategies.cleartext_storage_strategy
import backend.services.verification_strategies.cloud_bucket_strategy
import backend.services.verification_strategies.command_injection_strategy
import backend.services.verification_strategies.comment_disclosure_strategy
import backend.services.verification_strategies.cors_strategy
import backend.services.verification_strategies.cross_domain_policy_strategy
import backend.services.verification_strategies.csrf_strategy
import backend.services.verification_strategies.cswsh_strategy
import backend.services.verification_strategies.default_credentials_strategy
import backend.services.verification_strategies.directory_listing_strategy
import backend.services.verification_strategies.expression_language_strategy
import backend.services.verification_strategies.file_upload_strategy
import backend.services.verification_strategies.graphql_batching_strategy
import backend.services.verification_strategies.graphql_resolver_auth_strategy
import backend.services.verification_strategies.host_header_injection_strategy
import backend.services.verification_strategies.http_request_smuggling_strategy
import backend.services.verification_strategies.insecure_deserialization_strategy
import backend.services.verification_strategies.jwt_strategy
import backend.services.verification_strategies.ldap_injection_strategy
import backend.services.verification_strategies.local_file_inclusion_strategy
import backend.services.verification_strategies.mass_assignment_strategy
import backend.services.verification_strategies.nosql_injection_strategy
import backend.services.verification_strategies.oauth_redirect_uri_strategy
import backend.services.verification_strategies.oauth_state_parameter_strategy
import backend.services.verification_strategies.open_redirect_strategy
import backend.services.verification_strategies.parameter_tampering_strategy
import backend.services.verification_strategies.password_policy_strategy
import backend.services.verification_strategies.path_normalization_strategy
import backend.services.verification_strategies.path_traversal_strategy
import backend.services.verification_strategies.race_condition_strategy
import backend.services.verification_strategies.replay_attack_strategy
import backend.services.verification_strategies.session_fixation_strategy
import backend.services.verification_strategies.sql_injection_strategy
import backend.services.verification_strategies.ssrf_strategy
import backend.services.verification_strategies.ssti_strategy
import backend.services.verification_strategies.verbose_error_strategy
import backend.services.verification_strategies.web_cache_poisoning_strategy
import backend.services.verification_strategies.workflow_step_skipping_strategy
import backend.services.verification_strategies.xss_strategy
import backend.services.verification_strategies.xxe_strategy
